#!/bin/sh
mkdir -p .buildlibs
mkdir -p lib/lib
mkdir -p lib/include

cd .buildlibs

wget https://github.com/madlib-lang/raylib/archive/refs/heads/patch.zip
unzip patch.zip
cd raylib-patch
cd src


# CUSTOM_CFLAGS
make PLATFORM=PLATFORM_DESKTOP
cp libraylib.a ../../../lib/lib/
cp *.h ../../../lib/include/

cd ../../../

# build libsfml.a
make -C lib -j
